### ISSUE TITLE
exception null occured

### ISSUE THREAD

**Issue by xuehenIT** [OWASP/MSTG-Hacking-Playground#13]
when I have made 4 example, frida is listening , but no log can print on console and phone point out "exception null occured" . How can i resole the problem?

**Comment by xuehenIT** [comment]
> when I have made 4 example, frida is listening , but no log can print on console and phone point out "exception null occured" . How can i resole the problem?

nexus 5x 6.0 and frida 12.2.28

**Comment by commjoen** [comment]
Hi @xuehenIT , I was not "watching" this space yet. I now am, sorry for the late response! Will get back to you soon about this.

**Comment by commjoen** [comment]
Feel free to contact us through slack : https://join.slack.com/t/owasp/shared_invite/enQtNjExMTc3MTg0MzU4LTViMDg1MmJiMzMwZGUxZjgxZWQ1MTE0NTBlOTBhNjhhZDIzZTZiNmEwOTJlYjdkMzAxMGVhNDkwNDNiNjZiOWQ

**Comment by sushi2k** [comment]
Hi @xuehenIT. Are you referring to the Android App in Java and this test case https://github.com/OWASP/MSTG-Hacking-Playground/wiki/Android-App#omtg_datast_002_logging? 

You should be able to see the log output via logcat, no need for Frida.

**Comment by sushi2k** [comment]
Closing this issue. Please reopen @xuehenIT if needed. Thanks
