### ISSUE TITLE
C compiler failed while compiling native.c.

### ISSUE THREAD

**Issue by hxcc** [OWASP/MSTG-Hacking-Playground#5]
when i use Android Studio.
build failed.
C compiler failed while compiling native.c.

**Comment by sushi2k** [comment]
Hi @hxcc. For which app, the Java App or Kotlin app?

**Comment by commjoen** [comment]
Hi @hxcc , can you let us know a little bit more?

**Comment by commjoen** [comment]
Closing down the issue due to unresponsiveness. Feel free to file a bug-report again or contact us on OWASP Slack: https://join.slack.com/t/owasp/shared_invite/enQtNjExMTc3MTg0MzU4LTViMDg1MmJiMzMwZGUxZjgxZWQ1MTE0NTBlOTBhNjhhZDIzZTZiNmEwOTJlYjdkMzAxMGVhNDkwNDNiNjZiOWQ
